import { Deal } from "./types";

/**
 * Mock deal data for development and initial testing.
 * This will be replaced with real API data in production.
 */
export const MOCK_DEALS: Deal[] = [
  {
    id: "1",
    title: "삼성 갤럭시 버즈2 프로 노이즈캔슬링 무선 이어폰",
    deal_price: 149000,
    original_price: 229000,
    discount_percentage: 35,
    ai_score: 92,
    ai_reasoning: "높은 할인율과 우수한 제품 평가",
    deal_type: "flash_sale",
    deal_url: "https://www.coupang.com/vp/products/123456",
    image_url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    view_count: 1243,
    vote_up: 89,
    comment_count: 23,
    shop: {
      name: "쿠팡",
      slug: "coupang",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "노트북/모바일",
      slug: "laptop-mobile",
    },
  },
  {
    id: "2",
    title: "LG 그램 17인치 노트북 2024년형 17Z90S (i7/16GB/512GB)",
    deal_price: 1689000,
    original_price: 2190000,
    discount_percentage: 23,
    ai_score: 88,
    ai_reasoning: "프리미엄 제품 대폭 할인",
    deal_type: "price_drop",
    deal_url: "https://shopping.naver.com/product/123456",
    image_url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    view_count: 2341,
    vote_up: 156,
    comment_count: 45,
    shop: {
      name: "네이버쇼핑",
      slug: "naver",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "노트북/모바일",
      slug: "laptop-mobile",
    },
  },
  {
    id: "3",
    title: "다이슨 V15 무선청소기 디텍트 압솔루트 (AS 2년 / 로켓배송)",
    deal_price: 649000,
    original_price: 1090000,
    discount_percentage: 40,
    ai_score: 95,
    ai_reasoning: "베스트셀러 초특가",
    deal_type: "clearance",
    deal_url: "https://www.11st.co.kr/products/123456",
    image_url: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    view_count: 5234,
    vote_up: 412,
    comment_count: 89,
    shop: {
      name: "11번가",
      slug: "11st",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "가전/TV",
      slug: "electronics-tv",
    },
  },
  {
    id: "4",
    title: "애플 에어팟 프로 2세대 MQD83KH/A 정품",
    deal_price: 289000,
    original_price: 359000,
    discount_percentage: 19,
    ai_score: 85,
    ai_reasoning: "정품 최저가",
    deal_type: "coupon",
    deal_url: "https://www.gmarket.co.kr/item/123456",
    image_url: "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    view_count: 3421,
    vote_up: 234,
    comment_count: 67,
    shop: {
      name: "G마켓",
      slug: "gmarket",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "노트북/모바일",
      slug: "laptop-mobile",
    },
  },
  {
    id: "5",
    title: "로지텍 MX Master 3S 무선 마우스 블랙",
    deal_price: 119000,
    original_price: 149000,
    discount_percentage: 20,
    ai_score: 78,
    ai_reasoning: "인기 제품 할인",
    deal_type: "flash_sale",
    deal_url: "https://www.ssg.com/item/123456",
    image_url: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    view_count: 1876,
    vote_up: 123,
    comment_count: 34,
    shop: {
      name: "SSG.COM",
      slug: "ssg",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "PC/하드웨어",
      slug: "pc-hardware",
    },
  },
  {
    id: "6",
    title: "필립스 에어프라이어 XXL 7.3L HD9650/91",
    deal_price: 198000,
    original_price: 359000,
    discount_percentage: 45,
    ai_score: 91,
    ai_reasoning: "큰 할인폭, 우수 리뷰",
    deal_type: "clearance",
    deal_url: "https://www.lotteon.com/p/123456",
    image_url: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    view_count: 2987,
    vote_up: 276,
    comment_count: 58,
    shop: {
      name: "롯데온",
      slug: "lotteon",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "가전/TV",
      slug: "electronics-tv",
    },
  },
  {
    id: "7",
    title: "닌텐도 스위치 OLED 화이트 본체 정발",
    deal_price: 379000,
    original_price: 429000,
    discount_percentage: 12,
    ai_score: 82,
    ai_reasoning: "정품 할인",
    deal_type: "price_drop",
    deal_url: "https://www.coupang.com/vp/products/123457",
    image_url: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    view_count: 4123,
    vote_up: 345,
    comment_count: 92,
    shop: {
      name: "쿠팡",
      slug: "coupang",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "게임/SW",
      slug: "games-software",
    },
  },
  {
    id: "8",
    title: "삼성 비스포크 김치냉장고 RQ34C7931AP 327L 1등급",
    deal_price: 1289000,
    original_price: 1690000,
    discount_percentage: 24,
    ai_score: 87,
    ai_reasoning: "대형가전 파격 할인",
    deal_type: "flash_sale",
    deal_url: "https://shopping.naver.com/product/123457",
    image_url: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    view_count: 1654,
    vote_up: 98,
    comment_count: 21,
    shop: {
      name: "네이버쇼핑",
      slug: "naver",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "가전/TV",
      slug: "electronics-tv",
    },
  },
  {
    id: "9",
    title: "스타벅스 기프트카드 5만원권 (즉시발송)",
    deal_price: 47000,
    original_price: 50000,
    discount_percentage: 6,
    ai_score: 75,
    ai_reasoning: "상품권 할인",
    deal_type: "coupon",
    deal_url: "https://www.11st.co.kr/products/123457",
    image_url: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    view_count: 8765,
    vote_up: 654,
    comment_count: 124,
    shop: {
      name: "11번가",
      slug: "11st",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "상품권/쿠폰",
      slug: "gift-cards",
    },
  },
  {
    id: "10",
    title: "CJ 백설 햇반 210g x 24개입 (무료배송)",
    deal_price: 23900,
    original_price: 31200,
    discount_percentage: 23,
    ai_score: 79,
    ai_reasoning: "생필품 좋은 가격",
    deal_type: "price_drop",
    deal_url: "https://www.kurly.com/goods/123456",
    image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    view_count: 5432,
    vote_up: 432,
    comment_count: 76,
    shop: {
      name: "SSG",
      slug: "ssg",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "생활/식품",
      slug: "living-food",
    },
  },
  {
    id: "11",
    title: "샤오미 공기청정기 4 라이트 (관부가세 포함)",
    deal_price: 89000,
    original_price: 159000,
    discount_percentage: 44,
    ai_score: 90,
    ai_reasoning: "해외직구 특가",
    deal_type: "flash_sale",
    deal_url: "https://www.aliexpress.com/item/123456",
    image_url: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    view_count: 3210,
    vote_up: 287,
    comment_count: 54,
    shop: {
      name: "알리익스프레스",
      slug: "aliexpress",
      logo_url: null,
      country: "CN",
    },
    category: {
      name: "가전/TV",
      slug: "electronics-tv",
    },
  },
  {
    id: "12",
    title: "AMD 라이젠 7 7800X3D (정품) CPU",
    deal_price: 489000,
    original_price: 599000,
    discount_percentage: 18,
    ai_score: 93,
    ai_reasoning: "게이밍 CPU 베스트",
    deal_type: "price_drop",
    deal_url: "https://www.coupang.com/vp/products/123458",
    image_url: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400&h=300&fit=crop",
    is_active: true,
    expires_at: null,
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    view_count: 2876,
    vote_up: 198,
    comment_count: 43,
    shop: {
      name: "쿠팡",
      slug: "coupang",
      logo_url: null,
      country: "KR",
    },
    category: {
      name: "PC/하드웨어",
      slug: "pc-hardware",
    },
  },
];
